#ifndef _GNET_HOMETOWN_DEF_H_
#define _GNET_HOMETOWN_DEF_H_
namespace GNET
{
	enum HOMETOWN_CLASSID
	{
		HT_CLSID_SUBSTANCE 				= 0,
		HT_CLSID_STATE_BEGIN 			= 1,
		HT_CLSID_STATE 					= 1,
		HT_CLSID_STATE_NONE				= 2,
		HT_CLSID_STATE_DRYFREE			= 3,
		HT_CLSID_STATE_DRY				= 4,
		HT_CLSID_STATE_PESTFREE			= 5,
		HT_CLSID_STATE_PEST				= 6,
		HT_CLSID_STATE_WEEDFREE			= 7,
		HT_CLSID_STATE_WEED				= 8,
		HT_CLSID_STATE_WILT				= 9,
		HT_CLSID_STATE_HARVEST			= 10,
		HT_CLSID_STATE_SEED				= 11,
		HT_CLSID_STATE_SPROUT			= 12,
		HT_CLSID_STATE_IMMATURE			= 13,
		HT_CLSID_STATE_PREMATURE		= 14,
		HT_CLSID_STATE_MATURE			= 15,
		HT_CLSID_STATE_INCULT			= 16,
		HT_CLSID_STATE_CULT				= 17,
		HT_CLSID_STATE_PLOW				= 18,
		HT_CLSID_STATE_PLANT			= 19,
		HT_CLSID_STATE_ALLSTOLEN		= 20,
		HT_CLSID_STATE_CROPPROTECT		= 21,
		HT_CLSID_STATE_HIDE				= 22,
		HT_CLSID_STATE_FARMPROTECT		= 23,
		HT_CLSID_STATE_FARMSPEEDGROW	= 24,

		HT_CLSID_STATE_END				= 4096,
	};

	enum HOMETOWN_FARM_STATE //注意状态是有优先级的，ID小的状态会先检查是否有变迁
	{
		//states for crop
		HTF_STATE_CROP_BEGIN		= 0,
		HTF_STATE_DRYFREE			= HTF_STATE_CROP_BEGIN,
		HTF_STATE_DRY				= HTF_STATE_CROP_BEGIN+1,
		HTF_STATE_PESTFREE			= HTF_STATE_CROP_BEGIN+2,
		HTF_STATE_PEST				= HTF_STATE_CROP_BEGIN+3,
		HTF_STATE_WEEDFREE			= HTF_STATE_CROP_BEGIN+4,
		HTF_STATE_WEED				= HTF_STATE_CROP_BEGIN+5,
		HTF_STATE_WILT				= HTF_STATE_CROP_BEGIN+6,
		HTF_STATE_HARVEST			= HTF_STATE_CROP_BEGIN+7,
		HTF_STATE_SEED				= HTF_STATE_CROP_BEGIN+8,
		HTF_STATE_SPROUT			= HTF_STATE_CROP_BEGIN+9,
		HTF_STATE_IMMATURE			= HTF_STATE_CROP_BEGIN+10,
		HTF_STATE_PREMATURE			= HTF_STATE_CROP_BEGIN+11,
		HTF_STATE_MATURE			= HTF_STATE_CROP_BEGIN+12,
		HTF_STATE_ALLSTOLEN			= HTF_STATE_CROP_BEGIN+13,		//被偷光
		HTF_STATE_CROPPROTECTBEGIN	= HTF_STATE_CROP_BEGIN+14,		//防偷状态起始
		HTF_STATE_CROPPROTECTEND	= HTF_STATE_CROP_BEGIN+19,		//防偷状态结束
		
		HTF_STATE_CROP_END			= HTF_STATE_CROP_BEGIN+1023,
		
		//states for field
		HTF_STATE_FIELD_BEGIN		= HTF_STATE_CROP_END+1,

		HTF_STATE_INCULT			= HTF_STATE_FIELD_BEGIN,
		HTF_STATE_CULT				= HTF_STATE_FIELD_BEGIN+1,
		HTF_STATE_PLOW				= HTF_STATE_FIELD_BEGIN+2,
		HTF_STATE_PLANT				= HTF_STATE_FIELD_BEGIN+3,

		HTF_STATE_FIELD_END			= HTF_STATE_FIELD_BEGIN+1023,

		//states for farm
		HTF_STATE_FARM_BEGIN		= HTF_STATE_FIELD_END+1,
		HTF_STATE_FARMPROTECTBEGIN	= HTF_STATE_FARM_BEGIN,			//整个农场防偷状态起始
		HTF_STATE_FARMPROTECTEND	= HTF_STATE_FARM_BEGIN+5,
		HTF_STATE_FARMSPEEDGROWBEGIN= HTF_STATE_FARM_BEGIN+6,		//整个农场加速状态起始
		HTF_STATE_FARMSPEEDGROWEND	= HTF_STATE_FARM_BEGIN+11,
		HTF_STATE_FARM_END			= HTF_STATE_FARM_BEGIN+1023,


		//states for farm player
		HTF_STATE_PLAYER_BEGIN		= HTF_STATE_FARM_END+1,
		HTF_STATE_HIDE				= HTF_STATE_PLAYER_BEGIN,
		HTF_STATE_PLAYER_END		= HTF_STATE_PLAYER_BEGIN+1023,
	};

	enum HOMETOWN_ERRCODE
	{
		HT_ERR_SUCCESS 					= 0	,
		HT_ERR_NOTFRIEND					,	//不在对方好友列表中
		HT_ERR_POCKETFULL 					,	//包裹已满
		HT_ERR_POCKETPOS					,	//非法包裹位置
		HT_ERR_POCKETPOSFULL				,	//包裹位置已满
		HT_ERR_ITEMNOTFOUND					,	//没有找到指定物品
		HT_ERR_SEEDNOTFOUND					,	//无效的种子类型
		HT_ERR_FRUITNOTFOUND				,	//无效的果实类型
		HT_ERR_INVALIDCMDTYPE				,	//无效的命令类型
		HT_ERR_TARGETSTATEREJECT			,	//动作作用的目标在当前状态拒绝该操作
		HT_ERR_TARGETNOACCEPTSTATE			,	//动作作用的目标没有处在接受该操作的状态
		HT_ERR_INVALIDCOMPOID				,	//COMPO ID 不存在
		HT_ERR_NOTADDCOMPO					,	//未添加该组件
		HT_ERR_PACKETSIZE					,	//包大小不正确
		HT_ERR_ALREADYADDCOMPO				,	//不能重复添加组件
		HT_ERR_PLAYEROFFLINE				,	//玩家已经不在线
		HT_ERR_FARMFIELDNOTFOUND			,	//指定ID的地块不存在
		HT_ERR_HASNOCROP					,	//没有种作物
		HT_ERR_MAXLEVEL						,	//已经是最高级别
		HT_ERR_CHARMNOTENOUGH				,	//魅力值不够
		HT_ERR_MONEYNOTENOUGH				,	//金钱不够
		HT_ERR_MONEYEXCHGAMOUNT				,	//金钱兑换时，兑换的数额不正确
		HT_ERR_NOTFORSALE					,	//物品不能购买
		HT_ERR_CANNOTSELL					,	//物品不能卖
		HT_ERR_INVALIDNUM					,	//数目不对
		HT_ERR_BUYTOOMANY					,	//一次购买物品数量太多
		HT_ERR_CANNOTSELFTARGET				,	//目标不能是自身
		HT_ERR_INVALIDTARGETTYPE			,	//无效的目标类型
		HT_ERR_CANNOTUSE					,	//物品不能使用
		HT_ERR_ITEMNOTENOUGH				,	//物品数目不够
		HT_ERR_FARMINCULTFIELD				,	//地块还没开垦   		30
		HT_ERR_FARMLOVEFIELDBYSELF			,	//别动自己的爱心地
		HT_ERR_FARMNRMLFIELDBYOTHER			,	//别动好友的普通地
		HT_ERR_FARMLOVEFIELDUSED			,	//好友的爱心地已被人种了
		HT_ERR_FARMFIELDNOFRUIT				,	//没有果实了
		HT_ERR_FARMFIELDSTEALSELF			,	//不能偷自己
		HT_ERR_FARMFIELDSTEALLOVE			,	//不能偷爱心菜地
		HT_ERR_FARMFIELDREQUIRELEVEL		,	//等级不够
		HT_ERR_COOLDOWN						,	//在冷却
		HT_ERR_POSITEMMISMATCH				,	//包裹栏中没有该物品
		HT_ERR_PLANTLOVEFIELDMAX			,	//种植的爱心地数已经到达级别允许的最大数
		HT_ERR_HAVE_STOLEN_TOOMUCH			,	//偷窃数量过多       41
	};

	enum HOMETOWN_FARM_SPONSOR_COOLDOWN_TYPE
	{
		HTF_SPONSOR_COOLDOWN_STEAL = 0,
	};

	enum HOMETOWN_FARM_SELF_COOLDOWN_TYPE
	{
		HTF_SELF_COOLDOWN_START		= 1000000,	//0-HTF_SELF_COOLDOWN_START具在模板中填写
		HTF_SELF_COOLDOWN_EXCHGMONEY,
	};

	enum HOMETOWN_FARM_TIME
	{
		HTF_TIME_DRY 					= 4*3600	,		//从不干旱到干旱的时间间隔
		HTF_TIME_PEST					= 4*3600	,		//从不长虫到长虫的时间间隔
		HTF_TIME_WEED					= 4*3600	,		//从不长草到长草的时间间隔
		HTF_TIME_WILT					= 3*24*3600	,		//从有害状态枯死的时间间隔
		HTF_TIME_MATUREWILT				= 3*24*3600	,		//成熟以后多久不收获就枯死
		HTF_TIME_SHOWFARMSPEEDGROW		= 3600,				//农场的加速生长显示1小时
		HTF_TIME_COOLDOWN_STEAL 		= 24*3600,			//偷菜冷却时间24小时
		HTF_TIME_COOLDOWN_EXCHGMONEY 	= 24*3600,			//通用币兑换组件币要冷却1天
	};

	enum HOMETOWN_FARM_ACTION
	{
		HTF_ACTION_NONE 	= 0	,
		HTF_ACTION_VIEW			,	//查看
		HTF_ACTION_PLOW 		,	//犁地
		HTF_ACTION_SOW			,	//播种
		HTF_ACTION_WATER		,	//浇水
		HTF_ACTION_PEST			,	//杀虫
		HTF_ACTION_WEED			,	//除草
		HTF_ACTION_HARVEST		,	//收获
		HTF_ACTION_STEAL		,	//偷窃
		HTF_ACTION_CULT			,	//开垦
		HTF_ACTION_MAX			,
	};

	enum HOMETOWN_FARM_FIELD_TYPE
	{
		HTF_FIELD_TYPE_NONE = 0	,
		HTF_FIELD_TYPE_NORMAL 	,
		HTF_FIELD_TYPE_LOVE 	,
	};
};
#endif
