
#ifndef __GNET_LOGSERVER_CALLID
#define __GNET_LOGSERVER_CALLID

namespace GNET
{

enum CallID
{
};

enum ProtocolType
{
	PROTOCOL_STATINFOVITAL	=	59,
	PROTOCOL_STATINFO	=	60,
	PROTOCOL_REMOTELOGVITAL	=	61,
	PROTOCOL_REMOTELOG	=	62,
	PROTOCOL_LOGSTOCKCOMMISSION	=	12000,
	PROTOCOL_LOGSTOCKBALANCE	=	12001,
	PROTOCOL_LOGSTOCKTRANSACTION	=	12002,
};

};
#endif
