
#ifndef __GNET_GAUTHD_CALLID
#define __GNET_GAUTHD_CALLID

namespace GNET
{

enum CallID
{
	RPC_GQUERYPASSWD	=	502,
	RPC_MATRIXPASSWD	=	550,
	RPC_MATRIXPASSWD2	=	8066,
	RPC_MATRIXTOKEN	=	8070,
	RPC_USERLOGIN	=	15,
	RPC_USERLOGIN2	=	8067,
	RPC_USERLOGOUT	=	33,
	RPC_GETADDCASHSN	=	514,
	RPC_CASHSERIAL	=	8009,
	RPC_NETMARBLELOGIN	=	9004,
	RPC_NETMARBLEDEDUCT	=	9003,
};

enum ProtocolType
{
	PROTOCOL_QUERYUSERPRIVILEGE_RE	=	507,
	PROTOCOL_QUERYUSERFORBID_RE	=	509,
	PROTOCOL_KICKOUTUSER	=	10,
	PROTOCOL_ACCOUNTINGRESPONSE	=	504,
	PROTOCOL_AUTHDVERSION	=	8010,
	PROTOCOL_KEYEXCHANGE	=	2,
	PROTOCOL_STATUSANNOUNCE	=	6,
	PROTOCOL_ACCOUNTINGREQUEST	=	503,
	PROTOCOL_ANNOUNCEZONEID	=	505,
	PROTOCOL_ANNOUNCEZONEID2	=	523,
	PROTOCOL_ANNOUNCEZONEID3	=	527,
	PROTOCOL_GAME2AU	=	8039,
	PROTOCOL_QUERYUSERPRIVILEGE	=	506,
	PROTOCOL_QUERYUSERPRIVILEGE2	=	524,
	PROTOCOL_QUERYUSERFORBID	=	508,
	PROTOCOL_QUERYUSERFORBID2	=	525,
	PROTOCOL_GMKICKOUTUSER	=	354,
	PROTOCOL_GMFORBIDSELLPOINT	=	378,
	PROTOCOL_GMSHUTUP	=	356,
	PROTOCOL_TRANSBUYPOINT	=	616,
	PROTOCOL_ADDCASH	=	515,
	PROTOCOL_ADDCASH_RE	=	516,
	PROTOCOL_VERIFYMASTER	=	519,
	PROTOCOL_VERIFYMASTER_RE	=	520,
	PROTOCOL_MATRIXFAILURE	=	553,
	PROTOCOL_BILLINGREQUEST	=	9001,
	PROTOCOL_BILLINGBALANCE	=	9000,
	PROTOCOL_NETMARBLELOGOUT	=	9005,
};

};
#endif
