#ifndef __ONLINE_GAME_GS_PLAYER_CHAR_MODE_H__
#define __ONLINE_GAME_GS_PLAYER_CHAR_MODE_H__

enum
{
	PLAYER_CHAR_MODE_FASHION = 1,
	PLAYER_CHAR_MODE_MOUNT = 2,
	PLAYER_CHAR_MODE_FASHION_MASK = 3,
	PLAYER_CHAR_MODE_OFFLINE_AGENT_ACTIVE = 4,
	PLAYER_CHAR_MODE_OFFLINE_AGENT_TIME = 5,
};

#endif
