#ifndef __SKILL_STATEDEF_H__
#define __SKILL_STATEDEF_H__

namespace GNET
{
enum visible_state{
	// 通用状态
	VSTATE_DECHURT       = 1,  // 保护盾
	VSTATE_MAGICSHIELD   = 2,  // 魔法盾
	VSTATE_SLOW          = 3,  // 冰冻
	VSTATE_WRAP          = 4,  // 
	VSTATE_BLESSED       = 5,  // 
	VSTATE_SLEEP         = 6,  // 
	VSTATE_SILENT        = 7,  // 
	VSTATE_HPLEAK        = 8,  // 
	VSTATE_HPGEN         = 9,  // 
	VSTATE_INVINCIBLE    = 10, // 
	VSTATE_WEAK          = 11, // 
	VSTATE_MPLEAK        = 12, // 
	VSTATE_MPGEN         = 13, // 
	VSTATE_DIZZY         = 14, // 
	VSTATE_TASK          = 15, // 15-16
	VSTATE_ICESHIELD     = 17, 
	VSTATE_UNMOVED       = 18, 
	VSTATE_SECRET        = 19, 
	VSTATE_DISASTER      = 20, 
	VSTATE_GRACE         = 21, 
	VSTATE_CATCHPET		 = 25,
	VSTATE_FEAR			 = 26,

	VSTATE_ABSOLUTEAREA	 = 27, //领域效果

	VSTATE_MIRACLEBURSTXIAN = 33, //神迹爆发仙
	VSTATE_MIRACLEBURSTFO = 34, //神迹爆发佛
	VSTATE_MIRACLEBURSTMO = 35, //神迹爆发魔
	VSTATE_DARKNESS		 = 36, //黑暗术
	VSTATE_IGNITE		 = 37, //燃烧
	VSTATE_FROZEN		 = 38, //冰封效果
	VSTATE_COLDINJURE	 = 39, //冻伤效果
	VSTATE_DAMAGEMOVE	 = 40, //位移伤害
	VSTATE_TURNBUFF		 = 41, //逆转正面效果
	VSTATE_TURNDEBUFF	 = 42, //逆转负面效果
	VSTATE_ADDWEAK		 = 43, //附加虚弱
	VSTATE_ADDWRAP		 = 44, //附加定身
	VSTATE_ADDCHARM		 = 45, //附加魅惑
	VSTATE_ADDSLOW		 = 46, //附加减速
	VSTATE_ADDCOMMON	 = 47, //附加通用
	VSTATE_FIRING		 = 48, //焚香灼烧
	VSTATE_HUOZHU		 = 49, //火狩护主
	VSTATE_DECHURT2 	 = 50, //减伤2
	VSTATE_SENIORDARK	 = 51, //高等暗使
	VSTATE_SENIORLIGHT	 = 52, //高等光使
	//VSTATE_IMAGEMIRROR	 = 53, //镜像
	VSTATE_SHOWYB	 	 = 54, //镜像
	VSTATE_RECOVERYHP	 = 55, //恢复气血
};

enum hidden_state{
	HSTATE_DIZZY         = 1,    // 眩晕
	HSTATE_SLEEP         = 2,    // 睡眠
	HSTATE_WEAK          = 3,    // 虚弱
	HSTATE_SILENT        = 4,    // 沉默
	HSTATE_WRAP          = 5,    // 缠绕
	HSTATE_SLOW          = 6,    // 迟缓
	HSTATE_ADDATTACK     = 7,    // 增加攻击
	HSTATE_ADDDEFENCE    = 8,    // 增加防御
	HSTATE_INCATTACK     = 9,    // 铁拳
	HSTATE_INCDEFENCE    = 10,   // 硬皮

	HSTATE_ADDANTIDIZZY  = 11,   // 增加昏迷抗性
	HSTATE_ADDANTISLEEP  = 12,   // 
	HSTATE_ADDANTIWEAK   = 13,   // 增加虚弱抗性
	HSTATE_ADDANTISILENT = 14,   // 增加沉默抗性
	HSTATE_ADDANTIWRAP   = 15,   // 增加缠绕抗性

	HSTATE_SUBANTIDIZZY  = 16,   // 降低昏迷抗性
	HSTATE_SUBANTISLEEP  = 17,   // 降低睡眠抗性
	HSTATE_SUBANTIWEAK   = 18,   // 降低虚弱抗性
	HSTATE_SUBANTISILENT = 19,   // 降低沉默抗性
	HSTATE_SUBANTIWRAP   = 20,   // 降低缠绕抗性

	HSTATE_INCHP          = 21,   // 增加HP上限
	HSTATE_INCMP          = 22,   // 增加MP上限
	HSTATE_ADDHP          = 23,   // 增加HP上限
	HSTATE_ADDMP          = 24,   // 增加HP上限
	HSTATE_ADDSPEED       = 25,   // 神行
	HSTATE_ADDDODGE       = 26,   // 灵巧
	HSTATE_INCHPGEN       = 27,   // 生命恢复加快
	HSTATE_CRAZY          = 28,   // 精神燃烧
	HSTATE_HPLEAK         = 29,   // 中毒
	HSTATE_MPLEAK         = 30,   // 中毒
	HSTATE_HPGEN          = 31,   // 恢复生命
	HSTATE_MPGEN          = 32,   // 恢复魔力
	HSTATE_INCMPGEN       = 33,   // 魔力恢复加快
	HSTATE_SUBDEFENCE     = 34,   // 降低防御
	HSTATE_DECDEFENCE     = 35,   // 降低防御百分比
	HSTATE_IMMUNEDIZZY    = 36,   // 免疫缓慢
	HSTATE_IMMUNESLEEP    = 37,   // 免疫缓慢
	HSTATE_IMMUNESILENT   = 38,   // 免疫缓慢
	HSTATE_IMMUNEWEAK     = 39,   // 免疫缓慢
	HSTATE_IMMUNEWRAP     = 40,   // 免疫缠绕
	HSTATE_IMMUNESLOW     = 41,   // 免疫缓慢
	HSTATE_CURSED         = 42,   // 受攻击累计伤害
	HSTATE_POWERUP        = 43,   // 防御增强攻击降低
	HSTATE_BLOODSHIELD    = 44,   // 受伤害增加防御
	HSTATE_BLESSED        = 45,   // 
	HSTATE_SHOUYI         = 46,   // 降防减功固定值
	HSTATE_INVINCIBLE     = 47,   // 无敌
	HSTATE_DRUNK          = 48,   // 醉酒
	HSTATE_SPICY          = 49,   // 辣

	HSTATE_SUBHP	       = 50,   // 减少hp上限固定值 
	HSTATE_SUBMP	       = 51,   // 减少mp上限固定值
	HSTATE_SUBATTACK       = 52,   // 减少攻击固定值 
	HSTATE_DECCRITRATE     = 53,   // 减少目标爆机率 
	HSTATE_DECDODGE        = 54,   // 降低躲闪百分比
	HSTATE_FRENZIED        = 55,   // 受伤害增加攻击力
	HSTATE_INCHURT         = 56,   // 伤害增加百分比
	HSTATE_NINGJIN         = 57,   // 凝劲之术
	HSTATE_INCANTI         = 58,   // 增加所有抗性百分比
	HSTATE_ADDANTI         = 59,   // 增加所有抗性固定值
	HSTATE_DECANTI         = 60,   // 降低所有抗性百分比
	HSTATE_SUBANTI         = 61,   // 减少所有抗性固定值
	HSTATE_INCSKILLDAMAGE  = 62,   // 技能伤害增加百分比
	HSTATE_DECSKILLDAMAGE  = 63,   // 技能伤害减少百分比
	HSTATE_RETORT          = 64,   // 反震
	HSTATE_INCCRITHURT     = 65,   
	HSTATE_HPSUCK          = 66,  
	HSTATE_MPSUCK          = 67, 
	HSTATE_INCHEAL         = 68, 
	HSTATE_CYCSUBDEFENCE   = 69, 
	HSTATE_CYCSUBATTACK    = 70, 
	HSTATE_CYCDECDEFENCE   = 71, 
	HSTATE_CYCDECATTACK    = 72, 
	HSTATE_FAMILYINCHP     = 73, 
	HSTATE_FAMILYINCATTACK = 74, 
	HSTATE_FAMILYINCMP     = 75, 
	HSTATE_DECACCURACY     = 76, 
	HSTATE_DECCRITHURT     = 77,
	HSTATE_ICESHIELD       = 78,
	HSTATE_FOCUSANTI       = 79,
	HSTATE_DISPERSEANTI    = 80,
	HSTATE_BAREHANDED      = 81,
	HSTATE_MAGICSHIELD     = 82,
	HSTATE_DECHURT         = 83,
	HSTATE_DECDAMAGE       = 84,
	HSTATE_DIET            = 85,
	HSTATE_INCCRITRATE     = 86,
	HSTATE_POWERLESS       = 87,
	HSTATE_ALOOF           = 88,
	HSTATE_BLEEDING        = 89,
	HSTATE_DIZZYTIMER      = 90,
	HSTATE_WRAPTIMER       = 91,
	HSTATE_SILENTTIMER     = 92,
	HSTATE_SLEEPTIMER      = 93,
	HSTATE_HPLEAK1         = 94,
	HSTATE_HPLEAK2         = 95,
	HSTATE_HPLEAK3         = 96,
	HSTATE_GHOSTFORM       = 97,
	HSTATE_INSANITYFORM    = 98,
	HSTATE_DODGEREGAIN     = 99,
	HSTATE_HPREGAIN        = 100,
	HSTATE_DEADLYBLESS     = 101,
	HSTATE_HURTSCATTER     = 102,
	HSTATE_DEATHSCATTER    = 103,
	HSTATE_INCSKILLACCU    = 104,
	HSTATE_DECSKILLACCU    = 105,
	HSTATE_INCSKILLDODGE   = 106,
	HSTATE_DECSKILLDODGE   = 107,
	HSTATE_INCFATALRATIO   = 108,
	HSTATE_DECFATALRATIO   = 109,
	HSTATE_INCFATALHURT    = 110,
	HSTATE_DECFATALHURT    = 111,
	HSTATE_EXPBOOST        = 112,
	HSTATE_CREDITBOOST     = 113,
	HSTATE_REJECTDEBUFF    = 114,
	HSTATE_ADDATTACK2	   = 115,
	HSTATE_YANYU           = 116,
	HSTATE_HPLEAK4	       = 117,
	HSTATE_INCATTACK2	   = 118,
	HSTATE_HPLEAK5	   	   = 119,
	HSTATE_ADDHP2	   	   = 120,
	HSTATE_INCATTACK3	   = 121,
	HSTATE_INCHP2	       = 122,
	HSTATE_HPLEAK6	   	   = 123,
	HSTATE_ZHAOQI	   	   = 124,
	HSTATE_FASHEN	   	   = 125,
	HSTATE_CIBEI	   	   = 126,
	HSTATE_INCDEFENCE2	   = 127,
	HSTATE_ADDATTACK3	   = 128,
	HSTATE_TIANGU	   	   = 129,
	HSTATE_BANRUO	   	   = 130,
	HSTATE_XINMO	   	   = 131,
	HSTATE_AOSHI	   	   = 132,
	HSTATE_HUPO	   		   = 133,
	HSTATE_GUILIN	   	   = 134,
	HSTATE_ADDATTACK4	   = 135,
	HSTATE_ADDANTI2	   	   = 136,
	HSTATE_ADDDODGE2	   = 137,
	HSTATE_TONGXIN	   	   = 138,
	HSTATE_SLOW2           = 139,    // 迟缓
	HSTATE_BAREXPBOOST     = 140,
	HSTATE_BARHPGEN        = 141,   // 恢复生命
	HSTATE_BARMPGEN        = 142,   // 恢复生命
	HSTATE_BARADDDOGEACCU  = 143,
	HSTATE_VIPHUPO	   	   = 144,
	HSTATE_VIPGUILIN	   = 145,
	HSTATE_FEAR			   = 146,
	HSTATE_LONGXIANG	   = 147,
	HSTATE_HUJU			   = 148,
	HSTATE_DOUHUN		   = 149,
	HSTATE_GANGDAN		   = 150,
	HSTATE_ASWIND		   = 151,
	HSTATE_ASFOREST		   = 152,
	HSTATE_ASFIRE		   = 153,
	HSTATE_ASHILL		   = 154,
	HSTATE_MAKECRIT		   = 155,
	HSTATE_FOXSTATE		   = 156,
	HSTATE_CHANGEFORM	   = 157,	// 用于gs变身的时候,不对应filter
	HSTATE_CHIHUN		   = 158,
	HSTATE_EVILAURA		   = 159,
	HSTATE_HOLYAURA		   = 160,
	HSTATE_TRANSFORM	   = 161,       //技能变身
	HSTATE_TRANSFORM_TASK	   	= 162,       //任务变身
	HSTATE_IMMUNETRANSFORM     	= 163,       //变身免疫
	HSTATE_ADDANTITRANSFORM    	= 164,       //增加变身抗性
	HSTATE_SUBANTITRANSFORM    	= 165,       //降低变身抗性
	HSTATE_DIMMING		   	  	= 166,	//朦胧 
	HSTATE_SHADOWHIDE	   		= 167,   //影遁
	HSTATE_SHADOWDANCE	   		= 168,	//影舞
	HSTATE_SHARELIFEWITHCLONE  	= 169,	//与分身共享生命
	HSTATE_SHARESTATEWITHCLONE 	= 170,	//与分身共享状态
	HSTATE_BACKSTAB			   	= 171,	//背刺
	HSTATE_CRITCURSE		   	= 172, 	//暴击诅咒
	HSTATE_INCDRUGEFFECT	   	= 173, 	//增强吃药效果
	HSTATE_DECDRUGEFFECT	   	= 174,	//减弱吃药效果
	HSTATE_SKILLMIRROR		   	= 175,  //技能镜
	HSTATE_DRAWCLONELIFE		= 176, 	//吸取分身生命增加玩家生命最大值
	HSTATE_ABSOLUTEAREA			= 177, 	//领域
	HSTATE_ADDSPOT				= 178, 	//增加反隐能力
	HSTATE_SUBSPOT				= 179,  //降低反隐能力
	HSTATE_ADDHIDE				= 180,  //增加隐身能力
	HSTATE_SUBHIDE				= 181, 	//降低隐身能力
	HSTATE_FOGSTATE				= 182,  //五行遁
	
	HSTATE_MIRACLEBURSTXIAN		= 183,	//神迹爆发仙
	HSTATE_MIRACLEBURSTFO		= 184,	//神迹爆发佛
	HSTATE_MIRACLEBURSTMO		= 185,	//神迹爆发魔
	HSTATE_DARKNESS				= 186,	//黑暗术
	HSTATE_IGNITE				= 187,	//燃烧
	HSTATE_SKILLREFLECT			= 188,	//技能反射
	HSTATE_DIVINITYBURST		= 189,	//神圣爆发
	HSTATE_DIVINITYFURY			= 190,	//神圣之怒
	HSTATE_COLDINJURE			= 191,	//冻伤
	HSTATE_FROZEN				= 192,	//冰封术
	HSTATE_GOBACK				= 193,	//返回原来的位置
	HSTATE_SCOPEDAMAGE			= 194,	//范围内人数决定伤害
	HSTATE_PULLBACK				= 195,	//将单位拉到身边
	HSTATE_DAMAGEMOVE			= 196,	//位移伤害
	HSTATE_HUMANBOMB			= 197,	//人体炸弹
	HSTATE_DPGEN				= 198,  //恢复神力

	HSTATE_SPIRITDRAG			= 199,	//灵力牵引	
	HSTATE_FIRING				= 200, 	//灼烧
	HSTATE_DELAYCAST			= 201,	//延迟生效
	HSTATE_TURNBUFF				= 202,  //逆转正面
	HSTATE_TURNDEBUFF			= 203, 	//逆转负面
	HSTATE_ADDWEAK				= 204,	//附加虚弱
	HSTATE_ADDWRAP				= 205,  //附加缠绕
	HSTATE_ADDCHARM				= 206,	//附加魅惑
	HSTATE_ADDSLOW				= 207,	//附加减速
	HSTATE_PARALYSIS			= 208,	//麻痹
	HSTATE_SWIFT				= 209,	//迅疾
	HSTATE_TRIGGERSKILL			= 210,	//触发技能
	HSTATE_ACTIVE				= 211,	//激活
	HSTATE_CRIPPLED				= 212, 	//残废
	HSTATE_GUISHEN1				= 213,	//脱神1
	HSTATE_TUOLING1				= 214,  //归灵1
	HSTATE_PULL					= 215,  //拉扯
	HSTATE_BLOODTHIRSTY			= 216,	//嗜血
	HSTATE_CYCLE				= 217,	//阵法
	HSTATE_ADDCOMMON			= 218,	//附加普通
	HSTATE_INCSKILLLEVEL		= 219,	//增加技能等级
	HSTATE_SETSKILLLEVEL		= 220,	//设定技能等级
	HSTATE_INCMOUNTSPEED		= 221, 	//增加骑乘速度
	HSTATE_GUISHEN2				= 222,	//脱神2
	HSTATE_TUOLING2				= 223,  //归灵2
	HSTATE_JAILPERMITCYCLEAREA	= 224,
	HSTATE_JAILLIMITCYCLEAREA	= 225,
	HSTATE_PULLING				= 226,
	HSTATE_YUANLING				= 227,

	HSTATE_JUNIORDARK			= 228,
	HSTATE_JUNIORLIGHT			= 229,
	HSTATE_SENIORDARK			= 230,
	HSTATE_SENIORLIGHT			= 231,
	HSTATE_DARKUNIFORM			= 232,
	HSTATE_LIGHTUNIFORM			= 233,
	
	HSTATE_DECHURT2				= 234,
	HSTATE_RECORDPOS			= 235,
	HSTATE_FLY					= 236,
	HSTATE_MIRRORIMAGE			= 237,
	HSTATE_INSTANTSKILL			= 238,
	HSTATE_PZHILL				= 239,
	HSTATE_PZNOMOVE				= 240,
	HSTATE_PZCHAOS				= 241,
	HSTATE_PZVOID				= 242,
	HSTATE_BATTLEFLAG			= 243,
	HSTATE_AUTORES			    = 244,
	HSTATE_GTHPGEN				= 245,
	HSTATE_GTMPGEN				= 246,
	HSTATE_GTADDATTACKDEFENSE 	= 247,
	HSTATE_RECOVERHP			= 248,
	HSTATE_EQUIPEFFECT			= 249,
	HSTATE_KINDOMEXP            = 250,
	HSTATE_SPEEDTO		    = 251,
	HSTATE_PUPPETFORM		    = 252,
	HSTATE_PUPPETSKILL		= 253,
	HSTATE_SUBANTIDIZZY2		= 254,
	HSTATE_SUBANTISLEEP2		= 255,
	HSTATE_SUBANTIWEAK2		= 256,
	HSTATE_SUBANTISILENT2		= 257,
	HSTATE_SUBANTIWRAP2		= 258,
	HSTATE_SUBANTISLOW2		= 259,
	HSTATE_SUBHP2			= 260,
	HSTATE_SUBMP2			= 261,
	HSTATE_SEED			= 262,
	HSTATE_QILINFORM		= 263,
	HSTATE_RMHUMANFORM		= 264,
	HSTATE_CYCLESKILL		= 265,
	HSTATE_BUXIU			= 266,
	HSTATE_BETAUNTED2		= 267,
	HSTATE_ADDRAGE1			= 268,
	HSTATE_ADDRAGE2			= 269,
	HSTATE_SHARELIFEWITHSUMMON	= 270,
	HSTATE_PET_COMBINE1		= 271,
	HSTATE_PET_COMBINE2		= 272,
	HSTATE_ACCUMDAMAGE		= 273,
	HSTATE_BLOODPOOL		= 274,
	HSTATE_COD_COOLDOWN		= 275,
	HSTATE_GUIWANG_ADDMAXHP		= 276,
	HSTATE_GUIWANG_ADDDAMAGE	= 277,
	HSTATE_GUIWANG_ADDTENACIY	= 278,
	HSTATE_GUIWANG_ADDSKILLATTACK	= 279,
	HSTATE_GUIWANG_ADDANTICRIT	= 280,
	HSTATE_DSLEEP      	 	= 281,    // 深度睡眠

	
	
	HSTATE_SYSTEMSTART     		= 1000,
};

#define IMMUNEOVERAWE      0x00000001   //免疫震慑
#define IMMUNEBLIND        0x00000002   //免疫致盲
#define IMMUNEREPEL        0x00000004   //免疫击退
#define IMMUNEDRAINMAGIC   0x00000008   //免疫流蓝
#define IMMUNEDECDEFENCE   0x00000010   //免疫击退
#define IMMUNESUBDEFENCE   0x00000020   //免疫击退
#define IMMUNEDIZZY        0x00000040   //免疫昏迷
#define IMMUNEWEAK         0x00000080   //免疫虚弱
#define IMMUNESLOW         0x00000100   //免疫缓慢
#define IMMUNESILENT       0x00000200   //免疫沉默
#define IMMUNESLEEP        0x00000400   //免疫睡眠
#define IMMUNEWRAP         0x00000800   //免疫缠绕
#define IMMUNEDIET         0x00001000   //免疫缠绕
#define IMMUNEBAREHANDED   0x00002000   //免疫伤害加倍
#define IMMUNEHPLEAK       0x00004000   //免疫持续伤害
#define IMMUNETAUNT        0x00008000   //免疫嘲讽
#define IMMUNEMPDISPERSE   0x00010000   //免疫元神耗散
#define IMMUNEMPLEAK	   0x00020000	//免疫流魔
#define IMMUNETRANSFORM	   0x00040000	//免疫变身
#define IMMUNEFIRING       0x00080000   //免疫灼烧
#define IMMUNEIGNITE	   0x00100000	//免疫血咒
#define IMMUNEDECDEFSCALE  0x00200000	//免疫降低防御百分比

//以下为人物特有，上面为怪物模版定义的免疫
#define IMMUNEFROZE 	   0x20000000   //免疫冰封术
#define IMMUNEPULL	   0x40000000   //免疫拉扯 囚牢等
#define IMMUNEDAMAGE	   0x80000000   //免疫伤害

#define SKILL_IMMUNEATTACK 0x80

}

#endif
